class CONFIG_R:
	NODEFILE = 'nodesfile'
	EDGESFILE = 'edgesfile'
	BW = 'bw'
	SAMPLE = 'sample'
	MAXCOV = 'maxcov'
	REFGENOME = 'refgenome'
	GENCODE = 'gencode'
	ANNO = 'anno'
	GENESFILE = 'genesfile'
	DECOILVERSION = 'decoilvizversion'
	GTFFILE = 'gtffile'
	ROOT = 'root'
	ROOTREAL = 'rootreal'
	ROOTIMG = 'rootimg'
	GENESANNO = '/code/anno/genes.txt'
	# GENESANNO = '/Users/madag/Projects/PhD/github/decoil-viz/anno/genes.txt'
	FNAME = 'fname'
	TEMPLATE = 'template.Rmd'
	SUMMARYFILE = 'summaryfile'
	OUTPUT = '/output'
	WINDOW = 'window'
	FILTERSCORE = 'filtertop'
	FILTERTOP = 'filterscore'
	EXTENDALLOWEDCHR = 'extendallowedchr'
 
class ENV:
	IN_CONTAINER = 'IN_CONTAINER'
 
